@startuml
'https://plantuml.com/sequence-diagram

participant Router
participant RequestHandler as rh
participant Controller as ctrl
participant Function as func
participant UseCase as uc
participant Repository as repo

Router -> rh : DeleteAccount(context)
rh -> ctrl : DeleteAccount(request)
ctrl -> func : BindAndValidate(payload)
func --> ctrl : dto, nil
func x--> ctrl : nil, error
ctrl x--> rh : response, error
rh x--> Router : 400, error response
ctrl -> uc : DeleteSingleAccountById(dto)
uc -> repo : DeleteSingleAccountById(entity)
ctrl -> uc : DeleteMultipleAccountById(dto)
uc -> repo : DeleteMultipleAccountById(entity)
repo --> uc : nil
uc --> ctrl : nil
ctrl --> rh : response, nil
rh --> Router : 200, OK response
repo x--> uc : error
uc x--> ctrl : error
ctrl x--> rh : response, error
rh x--> Router : 400, error response

@enduml
