@startuml

!define TABLE_BORDER_COLOR #AAAAAA
!define TABLE_HEADER_COLOR #CCCCCC
!define TABLE_ROW_COLOR #EEEEEE
!define RELATION_COLOR #999999

!define ENTITY_START_ROW |||
!define ENTITY_END_ROW |||

!define PK_ROW (PK)
!define FK_ROW ~ FK ~
!define FIELD_ROW |

skinparam class {
    BorderColor TABLE_BORDER_COLOR
    HeaderBackgroundColor TABLE_HEADER_COLOR
    BackgroundColor TABLE_ROW_COLOR
}

entity "Profiles" as profiles {
    +AccountID PK_ROW INT
    FirstName FIELD_ROW VARCHAR
    LastName FIELD_ROW VARCHAR
    Address FIELD_ROW VARCHAR
    +City FK_ROW TINYINT
    +Province FK_ROW SMALLINT
    ZipCode FIELD_ROW VARCHAR
    PhoneNumber FIELD_ROW VARCHAR
}

@enduml
